name: CI

on:
  push:
    branches:
      - main
       - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use secrets from dev
        run: |
          echo "API_KEY: ${{ secrets.API_KEY }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
      - name: Install dependencies
        run: npm install
     
      
      - name: Run linters
        run: npm run lint    
      - name: Create backup
        run: |
         mkdir -p uploads
         echo "Archivo de prueba" > uploads/ejemplo.txt
         tar -czf backup.tar.gz uploads/

      - name: Upload backup artifact
        uses: actions/upload-artifact@v3
        with:
         name: backup-uploads
         path: backup.tar.gz

