name: Deploy to Production

on:
  workflow_dispatch:   
  push:
    branches:
      - main          

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
 

    steps:
      - name: Login to GHCR
        run: |
          echo "${{ secrets.API_KEY }}" | docker login ghcr.io -u dayanarojasdrp --password-stdin

      - name: Pull image
        run: |
          docker pull ghcr.io/dayanarojasdrp/mi-app:latest

      - name: Run container
        run: |
          docker run -d -p 3000:3000 ghcr.io/dayanarojasdrp/mi-app:latest
